/**
 * scan_local.cpp — Standalone CVE and CIS compliance scanner for manual testing.
 *
 * Exercises the same detection logic as the vuln_scan plugin without requiring
 * the full Yuzu agent build (no gRPC, no vcpkg, no agent core).
 *
 * Compile on macOS (with nlohmann for JSON rule loading):
 *   clang++ -std=c++23 \
 *     -I agents/plugins/vuln_scan/src \
 *     -I $(brew --prefix nlohmann-json)/include \
 *     -o scan_local scripts/scan_local.cpp
 *
 * Compile on macOS (without nlohmann, compiled-in rules only):
 *   clang++ -std=c++23 -DYUZU_NO_DYNAMIC_RULES \
 *     -I agents/plugins/vuln_scan/src \
 *     -o scan_local scripts/scan_local.cpp
 *
 * Compile on Linux (g++-13):
 *   g++-13 -std=c++23 \
 *     -I agents/plugins/vuln_scan/src \
 *     -o scan_local scripts/scan_local.cpp
 *
 * Run:
 *   ./scan_local              # CVE + CIS scan
 *   ./scan_local --cve        # CVE scan only
 *   ./scan_local --cis        # CIS checks only
 *   ./scan_local --inventory  # print installed apps and exit
 *
 * If content/cve_rules.json exists (generated by scripts/generate-cve-rules.py),
 * it is loaded automatically and merged with the compiled-in rules.
 */

#include "cve_rules.hpp"
#include "kernel_detection.hpp"
#include "cis_checks.hpp"

#include <algorithm>
#include <cstdio>
#include <iostream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#if defined(__linux__) || defined(__APPLE__)
#include <cstdlib>
#endif

// ── Minimal helpers copied from vuln_scan_plugin.cpp ─────────────────────────

struct AppInfo { std::string name, version; };

static bool icontains(std::string_view hay, std::string_view needle) {
    if (needle.empty()) return true;
    return std::search(hay.begin(), hay.end(), needle.begin(), needle.end(),
        [](char a, char b) {
            return std::tolower((unsigned char)a) == std::tolower((unsigned char)b);
        }) != hay.end();
}

static std::string run_cmd(const char* cmd) {
    std::string out;
    FILE* p = popen(cmd, "r");
    if (!p) return out;
    char buf[256];
    while (fgets(buf, sizeof(buf), p)) out += buf;
    pclose(p);
    return out;
}

static bool cmd_exists(const char* c) {
    return std::string("command -v ") + c + " >/dev/null 2>&1",
           system((std::string("command -v ") + c + " >/dev/null 2>&1").c_str()) == 0;
}

// ── Installed app enumeration (platform-specific) ────────────────────────────

#ifdef __linux__
static std::vector<AppInfo> get_installed_apps() {
    std::vector<AppInfo> apps;
    auto parse_lines = [&](const std::string& out, char sep) {
        std::istringstream ss(out);
        std::string line;
        while (std::getline(ss, line)) {
            auto pos = line.find(sep);
            if (pos != std::string::npos)
                apps.push_back({line.substr(0, pos), line.substr(pos + 1)});
        }
    };
    if (cmd_exists("dpkg-query")) {
        auto out = run_cmd("dpkg-query -W -f='${Package}|${Version}|${Status}\\n' 2>/dev/null");
        std::istringstream ss(out);
        std::string line;
        while (std::getline(ss, line)) {
            if (line.find("install ok installed") == std::string::npos) continue;
            std::istringstream ls(line);
            std::string name, version;
            std::getline(ls, name, '|');
            std::getline(ls, version, '|');
            apps.push_back({name, version});
        }
    } else if (cmd_exists("rpm")) {
        parse_lines(run_cmd(
            "rpm -qa --queryformat '%{NAME}|%{VERSION}-%{RELEASE}\\n' 2>/dev/null"), '|');
    } else if (cmd_exists("pacman")) {
        parse_lines(run_cmd("pacman -Q 2>/dev/null"), ' ');
    }
    return apps;
}
#elif defined(__APPLE__)
static std::vector<AppInfo> get_installed_apps() {
    std::vector<AppInfo> apps;
    auto out = run_cmd(
        "system_profiler SPApplicationsDataType -detailLevel mini 2>/dev/null"
        " | grep -E '^ {4}\\w|Version:'");
    std::istringstream ss(out);
    std::string line, cur_name, cur_ver;
    while (std::getline(ss, line)) {
        auto start = line.find_first_not_of(" \t");
        if (start == std::string::npos) continue;
        line = line.substr(start);
        if (line.rfind("Version:", 0) == 0) {
            cur_ver = line.substr(line.find(':') + 2);
        } else if (!line.empty() && line.back() == ':') {
            if (!cur_name.empty()) apps.push_back({cur_name, cur_ver});
            cur_name = line.substr(0, line.size() - 1);
            cur_ver.clear();
        }
    }
    if (!cur_name.empty()) apps.push_back({cur_name, cur_ver});
    if (cmd_exists("brew")) {
        auto brew = run_cmd("brew list --versions 2>/dev/null");
        std::istringstream bs(brew);
        std::string bl;
        while (std::getline(bs, bl)) {
            auto sp = bl.find(' ');
            if (sp != std::string::npos)
                apps.push_back({bl.substr(0, sp), bl.substr(sp + 1)});
        }
    }
    return apps;
}
#else
static std::vector<AppInfo> get_installed_apps() { return {}; }
#endif

// ── Scan functions ────────────────────────────────────────────────────────────

struct Finding { std::string severity, category, title, detail; };

// Load dynamic rules from content/cve_rules.json if present.
// Returns the number of rules loaded (0 if file absent or parse fails).
static int g_dynamic_rules_count = 0;
static std::vector<yuzu::vuln::CveRuleDynamic> load_dynamic_rules() {
    std::vector<yuzu::vuln::CveRuleDynamic> rules;
#ifndef YUZU_NO_DYNAMIC_RULES
    // Resolve relative to the directory containing this binary
    std::string json_path = "content/cve_rules.json";
    auto err = yuzu::vuln::load_rules_from_json(json_path, rules);
    if (err.empty()) {
        g_dynamic_rules_count = static_cast<int>(rules.size());
    }
#endif
    return rules;
}

static std::vector<Finding> cve_scan(const std::vector<yuzu::vuln::CveRuleDynamic>& dynamic_rules) {
    std::vector<Finding> findings;
    auto apps = get_installed_apps();

    auto match = [&](std::string_view product, std::string_view affected_below,
                     std::string_view severity, std::string_view cve_id,
                     std::string_view description, std::string_view fixed_in) {
        for (const auto& app : apps) {
            if (!icontains(app.name, product) || app.version.empty()) continue;
            if (yuzu::vuln::compare_versions_normalized(app.version,
                    std::string(affected_below)) < 0) {
                findings.push_back({
                    std::string(severity), "cve",
                    std::string(cve_id) + ": " + std::string(description),
                    app.name + " " + app.version + " (fixed in " + std::string(fixed_in) + ")"
                });
            }
        }
    };

    for (const auto& r : yuzu::vuln::kCveRules)
        match(r.product, r.affected_below, r.severity, r.cve_id, r.description, r.fixed_in);

    for (const auto& r : dynamic_rules)
        match(r.product, r.affected_below, r.severity, r.cve_id, r.description, r.fixed_in);

    return findings;
}

static std::vector<Finding> kernel_scan() {
    std::vector<Finding> findings;
    auto ki = yuzu::vuln::get_kernel_info();
    if (ki.full_version.empty()) return findings;

    std::string_view product = ki.platform == "linux"   ? "linux-kernel"   :
                               ki.platform == "windows" ? "windows-kernel" :
                                                          "macos";
    for (const auto& r : yuzu::vuln::kCveRules) {
        if (!icontains(product, r.product)) continue;
        if (yuzu::vuln::compare_versions_normalized(ki.full_version,
                std::string(r.affected_below)) < 0) {
            findings.push_back({
                std::string(r.severity), "kernel",
                std::string(r.cve_id) + ": " + std::string(r.description),
                "kernel " + ki.full_version + " (fixed in " + std::string(r.fixed_in) + ")"
            });
        }
    }
    return findings;
}

static std::vector<Finding> cis_scan() {
    std::vector<Finding> findings;
    for (const auto& c : yuzu::vuln::run_all_cis_checks()) {
        findings.push_back({
            c.status == "FAIL" ? c.severity : "INFO",
            "cis",
            c.check_id + " [L" + c.level + "]: " + c.title,
            "status=" + c.status + "  expected=" + c.expected + "  actual=" + c.actual
                + "  fix: " + c.remediation
        });
    }
    return findings;
}

// ── Output ────────────────────────────────────────────────────────────────────

static constexpr int kColWidth = 10;

static void print_finding(const Finding& f) {
    // Color-code severity to terminal
    const char* color = "";
    const char* reset = "\033[0m";
    if      (f.severity == "CRITICAL") color = "\033[1;31m";  // bold red
    else if (f.severity == "HIGH")     color = "\033[31m";    // red
    else if (f.severity == "MEDIUM")   color = "\033[33m";    // yellow
    else if (f.severity == "LOW")      color = "\033[36m";    // cyan
    else                               color = "\033[2m";     // dim (INFO/PASS)

    // Only print non-INFO findings unless we'd have nothing
    std::printf("%s%-9s%s  [%-6s]  %s\n           %s\n\n",
        color, f.severity.c_str(), reset,
        f.category.c_str(),
        f.title.c_str(),
        f.detail.c_str());
}

static void print_summary(const std::vector<Finding>& findings) {
    int critical = 0, high = 0, medium = 0, low = 0;
    for (const auto& f : findings) {
        if (f.severity == "CRITICAL") ++critical;
        else if (f.severity == "HIGH") ++high;
        else if (f.severity == "MEDIUM") ++medium;
        else if (f.severity == "LOW") ++low;
    }
    std::printf("\033[1m─── Summary ───────────────────────────────────────\033[0m\n");
    if (critical) std::printf("\033[1;31m  CRITICAL: %d\033[0m\n", critical);
    if (high)     std::printf("\033[31m  HIGH    : %d\033[0m\n", high);
    if (medium)   std::printf("\033[33m  MEDIUM  : %d\033[0m\n", medium);
    if (low)      std::printf("\033[36m  LOW     : %d\033[0m\n", low);
    std::printf("  Total findings: %zu\n\n", findings.size());
}

static std::string csv_escape(const std::string& s) {
    // Wrap in quotes and escape internal quotes per RFC 4180
    std::string out = "\"";
    for (char c : s) {
        if (c == '"') out += "\"\"";
        else out += c;
    }
    out += '"';
    return out;
}

int main(int argc, char* argv[]) {
    bool do_cve = true, do_cis = true, do_inventory = false, do_csv = false;
    for (int i = 1; i < argc; ++i) {
        std::string_view arg = argv[i];
        if (arg == "--cve")       { do_cve = true;  do_cis = false; }
        if (arg == "--cis")       { do_cve = false; do_cis = true; }
        if (arg == "--inventory") { do_inventory = true; do_cve = false; do_cis = false; }
        if (arg == "--csv")       { do_csv = true; }
    }

    // Load dynamic rules once at startup
    auto dynamic_rules = load_dynamic_rules();
    if (!do_csv) {
        std::printf("\033[2mRules: %zu compiled-in",  yuzu::vuln::kCveRules.size());
        if (g_dynamic_rules_count > 0)
            std::printf(" + %d from content/cve_rules.json", g_dynamic_rules_count);
        else
            std::printf(" (no content/cve_rules.json found — run generate-cve-rules.py to add more)");
        std::printf("\033[0m\n\n");
    }

    if (do_inventory) {
        std::printf("Installed software:\n");
        for (const auto& a : get_installed_apps())
            std::printf("  %-40s %s\n", a.name.c_str(), a.version.c_str());
        return 0;
    }

    std::vector<Finding> all;

    if (do_cve) {
        auto ki = yuzu::vuln::get_kernel_info();
        if (!do_csv)
            std::printf("\033[1m─── Kernel: %s %s ───────────────────────────────────\033[0m\n",
                        ki.platform.c_str(), ki.full_version.c_str());
        auto kf = kernel_scan();
        for (const auto& f : kf) { if (!do_csv) print_finding(f); all.push_back(f); }

        if (!do_csv)
            std::printf("\033[1m─── CVE Scan (installed software) ──────────────────\033[0m\n");
        auto cf = cve_scan(dynamic_rules);
        if (cf.empty() && !do_csv) std::printf("  \033[2mNo CVEs matched.\033[0m\n\n");
        for (const auto& f : cf) { if (!do_csv) print_finding(f); all.push_back(f); }
    }

    if (do_cis) {
        if (!do_csv)
            std::printf("\033[1m─── CIS Level 1 Compliance Checks ─────────────────\033[0m\n");
        auto cisf = cis_scan();
        int fails = 0;
        for (const auto& f : cisf) {
            if (f.detail.find("status=FAIL") != std::string::npos) {
                if (!do_csv) print_finding(f);
                all.push_back(f);
                ++fails;
            }
        }
        if (!do_csv) {
            int total_checks = static_cast<int>(cisf.size());
            std::printf("  %d/%d checks FAILED  (%d passed)\n\n",
                        fails, total_checks, total_checks - fails);
        }
    }

    if (do_csv) {
        std::printf("severity,category,cve_id,description,detail\n");
        for (const auto& f : all) {
            // Split title into cve_id and description at first ": "
            std::string cve_id, description;
            auto sep = f.title.find(": ");
            if (sep != std::string::npos) {
                cve_id      = f.title.substr(0, sep);
                description = f.title.substr(sep + 2);
            } else {
                description = f.title;
            }
            std::printf("%s,%s,%s,%s,%s\n",
                csv_escape(f.severity).c_str(),
                csv_escape(f.category).c_str(),
                csv_escape(cve_id).c_str(),
                csv_escape(description).c_str(),
                csv_escape(f.detail).c_str());
        }
        return 0;
    }

    print_summary(all);
    return 0;
}
